-- One-time import of the 2026-27 weeks that count (Sep 6 onward) from the
-- BSM Bat Banner spreadsheet. Generated; see PR description for how values
-- were converted. Run once, after 0003_battalion_banner.sql.

INSERT INTO banner_weeks (start_date, end_date, strength_a, strength_b, strength_c, status, announced_json, finalized_at, finalized_by) VALUES ('2026-09-06', '2026-09-12', 54, 53, 53, 'final', '{"scores":{"A":13,"B":18,"C":14},"places":{"A":1,"B":3,"C":2},"winners":["A"],"source":"spreadsheet"}', '2026-09-12 12:00:00', 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_audit (week_id, action, actor, reason) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-06'), 'import', 'Imported from BSM Bat Banner.xlsx', 'Imported from sheet "Sep 6-12"');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-06'), 'rooms', '2026-09-08', 37, 46, 37, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-06'), 'rooms', '2026-09-10', 3, 5, 5, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-06'), 'atvs', '2026-09-08', 4, 6, 2, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-06'), 'bed_checks', '2026-09-11', 0, 4, 2, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');

INSERT INTO banner_weeks (start_date, end_date, strength_a, strength_b, strength_c, status, announced_json, finalized_at, finalized_by) VALUES ('2026-09-13', '2026-09-20', 54, 53, 53, 'final', '{"scores":{"A":15,"B":24,"C":13},"places":{"A":2,"B":3,"C":1},"winners":["C"],"source":"spreadsheet"}', '2026-09-20 12:00:00', 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_audit (week_id, action, actor, reason) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'import', 'Imported from BSM Bat Banner.xlsx', 'Imported from sheet "Sep 13-20"');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'rooms', '2026-09-15', 36, 42, 28, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'rooms', '2026-09-17', 4, 7, 4, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'accountability', '2026-09-13', 0, 2, 0, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'atvs', '2026-09-18', 2, 3, 2, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'common_area', '2026-09-18', 2, 3, 0, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'bat_staff', '2026-09-18', 0, 3, 2, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'bsm_brc', '2026-09-14', 1, 0, 0, 11, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-13'), 'bsm_brc', '2026-09-18', 0, 1, 1, NULL, 8, 12, 'Imported from BSM Bat Banner.xlsx');

INSERT INTO banner_weeks (start_date, end_date, strength_a, strength_b, strength_c, status, announced_json, finalized_at, finalized_by) VALUES ('2026-09-20', '2026-09-27', 54, 53, 53, 'final', '{"scores":{"A":14,"B":19,"C":14},"places":{"A":1,"B":3,"C":1},"winners":["A","C"],"source":"spreadsheet"}', '2026-09-27 12:00:00', 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_audit (week_id, action, actor, reason) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'import', 'Imported from BSM Bat Banner.xlsx', 'Imported from sheet "Sep 20 - 27"');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'rooms', '2026-09-22', 23, 41, 18, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'atvs', '2026-09-22', 4, 4, 1, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'common_area', '2026-09-24', 1, 3, 2, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'parade_retreat', '2026-09-24', 1, 5, 3, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'laundry', '2026-09-25', 1, 1, 1, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');
INSERT INTO banner_events (week_id, category, event_date, gigs_a, gigs_b, gigs_c, inspected_a, inspected_b, inspected_c, entered_by) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-20'), 'regimental', '2026-09-25', 0, 1, 0, NULL, NULL, NULL, 'Imported from BSM Bat Banner.xlsx');

INSERT INTO banner_weeks (start_date, end_date, strength_a, strength_b, strength_c, status, announced_json, finalized_at, finalized_by) VALUES ('2026-09-27', '2026-10-04', 54, 53, 53, 'open', NULL, NULL, NULL);
INSERT INTO banner_audit (week_id, action, actor, reason) VALUES ((SELECT id FROM banner_weeks WHERE start_date = '2026-09-27'), 'import', 'Imported from BSM Bat Banner.xlsx', 'Imported from sheet "Sep 27 - Oct"');

